name: 🐛 Bug Report
description: Create a new ticket for a bug.
title: "🐛 [Bug] - <title>"
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Issue description
      description: |
        Describe your issue briefly. What doesn't work, and how do you expect it to work instead?
      value: "A bug happened!"
    validations:
      required: true
  
  - type: input
    attributes:
      label: System information
      description: Specify the OS version and relevant hardware information.
    validations:
      required: false

  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Please enter an explicit description of your issue
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
      value: |
        ![DESCRIPTION](LINK.png)
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If you have any relevant log output, please copy and paste it. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false